version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "testdb"
    volumes:
      - /Users/kenny/kenny-source/Volumes/docker/postgres:/var/lib/postgresql/data