# 글로벌 셋팅
spring:
  application:
    name: 'spring-security'
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      # 디폴트 : 10
      maximum-pool-size: 10
      # 디폴트 : 30000( 30초 )
      connection-timeout: 10000
      # 디폴트 : 180000( 30분 )
      max-lifetime: 180000

server:
  port: 8080
---
